#include "processor_properties.h"
#include "../processor_src/processor_cmd.h"

cmd_struct possible_cmd[] = {{"PUSH",     PUSH,     number,     proc_push},
                             {"PUSHREG",  PUSHREG,  string,     proc_pushreg},
                             {"POPREG",   POPREG,   string,     proc_popreg},
                             {"PUSHM",    PUSHM,    ind,        proc_pushm},
                             {"POPM",     POPM,     ind,        proc_popm},
                             {"ADD",      ADD,      none,       proc_calc_binary},
                             {"SUB",      SUB,      none,       proc_calc_binary},
                             {"DIV",      DIV,      none,       proc_calc_binary},
                             {"MULT",     MULT,     none,       proc_calc_binary},
                             {"SQRT",     SQRT,     none,       proc_calc_unary},
                             {"IN",       IN,       none,       proc_in},
                             {"OUT",      OUT,      none,       proc_out},
                             {"JMP",      JMP,      number,     proc_jmp},
                             {"JB",       JB,       number,     proc_cond_jmp},
                             {"JBE",      JBE,      number,     proc_cond_jmp},
                             {"JA",       JA,       number,     proc_cond_jmp},
                             {"JAE",      JAE,      number,     proc_cond_jmp},
                             {"JE",       JE,       number,     proc_cond_jmp},
                             {"JNE",      JNE,      number,     proc_cond_jmp},
                             {"DMP",      DMP,      none,       proc_dmp},
                             {"DMPM",     DMPM,     none,       proc_dmpm},
                             {"CALL",     CALL,     label,      proc_call},
                             {"RET",      RET,      none,       proc_ret},
                             {"DRAW",     DRAW,     none,       proc_draw},
                             {"HLT",      HLT,      none,       proc_hlt}};
